name: Podman-Runner

on:
  push:
    paths:
    - './images/podman-runner/Dockerfile'
  workflow_dispatch:

# env:
#   FILTER_REGEX_INCLUDE: ./images/podman-runner/*

jobs:
  build-podman-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -   
        name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DCKR_PODMAN_RUNNER }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./images/podman-runner
          push: true
          tags: docker.io/shaker242/podman-runner:v${{github.run_number}}
